<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_concat(Showing you results for , , Bangal_e4cf7a</name>
   <tag></tag>
   <elementGuidId>dfb1679c-f2d1-426a-9a89-4a4f66292dbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ExploreLayoutController']/div/div/div/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/span/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a._15tommw</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/rooms/31917901?adults=1&amp;children=1&amp;check_in=2020-12-04&amp;check_out=2020-12-05&amp;previous_page_section_name=1000&amp;federated_search_id=474e49ab-1e30-466f-8689-b7995ec604b1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>listing_31917901</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>⚡COUPLE FRIENDLY BALI THEMED STAY</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_15tommw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExploreLayoutController&quot;)/div[@class=&quot;_e296pg&quot;]/div[1]/div[@class=&quot;_8h8epe3&quot;]/div[@class=&quot;_twmmpk&quot;]/div[@class=&quot;_19qnt1y&quot;]/div[@class=&quot;_1gw6tte&quot;]/div[@class=&quot;_uhpzdny&quot;]/div[1]/div[2]/div[1]/div[1]/div[1]/div[@class=&quot;_fhph4u&quot;]/div[@class=&quot;_8ssblpx&quot;]/div[@class=&quot;_gig1e7&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;_1048zci&quot;]/div[@class=&quot;_1nz9l7j&quot;]/div[@class=&quot;_2n7voam&quot;]/div[@class=&quot;_e296pg&quot;]/div[@class=&quot;_gjw2an&quot;]/div[@class=&quot;_1szwzht&quot;]/span[1]/div[@class=&quot;_ttw0d&quot;]/a[@class=&quot;_15tommw&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ExploreLayoutController']/div/div/div/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/span/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/rooms/31917901?adults=1&amp;children=1&amp;check_in=2020-12-04&amp;check_out=2020-12-05&amp;previous_page_section_name=1000&amp;federated_search_id=474e49ab-1e30-466f-8689-b7995ec604b1')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/a</value>
   </webElementXpaths>
</WebElementEntity>
